import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/views/appbars/navbar";
import WishListDrawer from "@/components/drawers/WishListDrawer";
import SidecartDrawer from "@/components/drawers/SidecartDrawer";
import PurchaseModal from "@/components/modals/PurchaseModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Astro Toothpaste Bits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <SidecartDrawer/>
        <WishListDrawer/>
        <PurchaseModal/>
        {children}
      </body>
    </html>
  );
}
